### ISSUE TITLE
[SECURITY] Non-Compliance : Transaction Gas Cost Calculation in LEVM

### ISSUE THREAD

**Issue by Lexterl33t** [lambdaclass/ethrex#1364]
Our team at [FuzzingLabs](https://github.com/FuzzingLabs) discovered a new non-compliance in the `LEVM` implementation violates Ethereum's specifications regarding the handling of gas costs during transaction creation. Specifically, the cost of creating a transaction is calculated and applied **after execution** in `LEVM`, whereas the Ethereum specifications dictate that this cost must be calculated and applied **at the beginning of the transaction**, prior to any execution.

This issue 

## Root cause

This non compliance occurs in the following function : [transact](https://github.com/lambdaclass/ethrex/blob/main/crates/vm/levm/src/vm.rs#L518)
```rust
    pub fn transact(&mut self) -> Result<TransactionReport, VMError> {
        let initial_gas = Default::default();

        self.env.consumed_gas = initial_gas;

        let mut current_call_frame = self
            .call_frames
            .pop()
            .ok_or(VMError::Internal(InternalError::CouldNotPopCallframe))?;

        self.validate_transaction(&mut current_call_frame)?;

        let mut report = self.execute(&mut current_call_frame)?;

        let initial_call_frame = self
            .call_frames
            .last()
            .ok_or(VMError::Internal(
                InternalError::CouldNotAccessLastCallframe,
            ))?
            .clone();

        let sender = initial_call_frame.msg_sender;

        let calldata_cost =
            gas_cost::tx_calldata(&initial_call_frame.calldata).map_err(VMError::OutOfGas)?;

        report.gas_used = report
            .gas_used
            .checked_add(calldata_cost)
            .ok_or(VMError::OutOfGas(OutOfGasError::GasUsedOverflow))?;

        if self.is_create() {
            // If create should check if transaction failed. If failed should revert (delete created contract, )
            if let TxResult::Revert(error) = report.result {
                self.revert_create()?;
                return Err(error);
            }
            let contract_code = report.clone().output;

            // TODO: Is this the expected behavior?
            if !contract_code.is_empty() {
                // (6)
                if contract_code.len() > MAX_CODE_SIZE {
                    return Err(VMError::ContractOutputTooBig);
                }
                // Supposing contract code has contents
                if *contract_code
                    .first()
                    .ok_or(VMError::Internal(InternalError::TriedToIndexEmptyCode))?
                    == INVALID_CONTRACT_PREFIX
                {
                    return Err(VMError::InvalidInitialByte);
                }
            }

            // If the initialization code completes successfully, a final contract-creation cost is paid,
            // the code-deposit cost, c, proportional to the size of the created contract’s code
            let number_of_words: u64 = initial_call_frame
                .calldata
                .chunks(WORD_SIZE)
                .len()
                .try_into()
                .map_err(|_| VMError::Internal(InternalError::ConversionError))?;

            let code_length: u64 = contract_code
                .len()
                .try_into()
                .map_err(|_| VMError::Internal(InternalError::ConversionError))?;

            let creation_cost =
                gas_cost::tx_creation(code_length, number_of_words).map_err(VMError::OutOfGas)?;
            report.gas_used = report
                .gas_used
                .checked_add(creation_cost)
                .ok_or(VMError::OutOfGas(OutOfGasError::GasUsedOverflow))?;
            // Charge 22100 gas for each storage variable set

            let contract_address = initial_call_frame.to;

            self.update_account_bytecode(contract_address, contract_code)?;
        }

        let coinbase_address = self.env.coinbase;

        self.decrease_account_balance(
            sender,
            U256::from(report.gas_used)
                .checked_mul(self.env.gas_price)
                .ok_or(VMError::GasLimitPriceProductOverflow)?,
        )?;

        let receiver_address = initial_call_frame.to;
        // If execution was successful we want to transfer value from sender to receiver
        if report.is_success() {
            // Subtract to the caller the gas sent
            self.decrease_account_balance(sender, initial_call_frame.msg_value)?;
            self.increase_account_balance(receiver_address, initial_call_frame.msg_value)?;
        }

        // Send coinbase fee
        let priority_fee_per_gas = self
            .env
            .gas_price
            .checked_sub(self.env.base_fee_per_gas)
            .ok_or(VMError::GasPriceIsLowerThanBaseFee)?;
        let coinbase_fee = (U256::from(report.gas_used))
            .checked_mul(priority_fee_per_gas)
            .ok_or(VMError::BalanceOverflow)?;

        self.increase_account_balance(coinbase_address, coinbase_fee)?;

        report.new_state.clone_from(&self.cache);

        Ok(report)
    }
```

In the provided `transact` function, the transaction's gas consumption is calculated and adjusted as follows:

1. **Gas Initialization**:
    - `self.env.consumed_gas` is initially set to `Default::default()`, which implies no gas is deducted at the start of the transaction.
2. **Execution Phase**:
    - The transaction executes via `self.execute(&mut current_call_frame)` without considering the upfront gas cost for creation. Gas adjustments for calldata and contract creation are calculated later in the flow.
3. **Gas Calculation and Application**:
    - For contract creation, gas costs are computed and added to the `report.gas_used` field **after execution**, as seen here:
    
    ```rust
    let creation_cost =
        gas_cost::tx_creation(code_length, number_of_words).map_err(VMError::OutOfGas)?;
    report.gas_used = report
        .gas_used
        .checked_add(creation_cost)
        .ok_or(VMError::OutOfGas(OutOfGasError::GasUsedOverflow))?;
    ```
    
4. **Final Gas Deduction**:
    - The sender's balance is adjusted at the end of the process, considering the gas used and gas price:
    
    ```rust
    sender_account.info.balance = sender_account
        .info
        .balance
        .checked_sub(
            U256::from(report.gas_used)
                .checked_mul(self.env.gas_price)
                .ok_or(VMError::GasLimitPriceProductOverflow)?,
        )
        .ok_or(VMError::BalanceUnderflow)?;
    ```
    

### **Expected Behavior According to Ethereum Specifications**

The Ethereum Yellow Paper specifies that the gas cost for a transaction, including calldata and creation costs, must be **calculated and deducted at the start of the transaction execution**. This ensures that:

1. **Pre-checks for Gas Availability**:
    - The system verifies whether the sender has sufficient balance and gas to proceed with the transaction before executing any part of it.
2. **Consistency Across Call Frames**:
    - The initial call frame (stack frame) should already include the adjusted gas available for execution, reflecting the upfront deduction.
3. **Gas Deduction Order**:
    - The gas for calldata, contract creation, and other transaction-related costs must be subtracted **before** executing any instructions in the transaction :
    
    ```rust
    Contract creation cost before executing any bytecode :
    consumed_gas = creation_cost + transaction_cost + initcode_word_cost + GTxDataNonZero_cost + GtxdataZero_cost 
    gas_limit -= consumed_gas
    ```
    

## **Impact of Non-Compliance**

The observed behavior can lead to the following issues:

1. **Incorrect Gas Handling**:
    - Gas that should have been reserved for transaction creation may be used during execution, potentially leading to an out-of-gas error or miscalculations in state transitions.
2. **Inconsistent State**:
    - The initial state of the call frame does not reflect the correct gas available, deviating from Ethereum’s standard behavior.

## Step to reproduce

**Payload**

```rust
[90]
GAS

Gas cost :
consumed_gas = creation_cost + transaction_cost + initcode_word_cost + GTxDataNonZero_cost + GtxdataZero_cost + gas_opcode_cost
consumed_gas = 32000 + 21000 + 2  + 16 + 2 = 53020
gas_limit = 100_000_000 - 53020 = 99946980
```

Add to [test](https://github.com/lambdaclass/ethrex/blob/5bbe595ff9e3900b2d84f075d3b19672a10854b9/crates/vm/levm/tests/edge_case_tests.rs) :

```rust
#[test]
fn test_non_compliance_gas_cost_transact() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[90]
    ))
    .unwrap();
    vm.env.gas_limit = U256::from(100_000_000);
    vm.transact();
    assert_eq!(vm.call_frames.pop().unwrap().stack.stack[0], U256::from(99946980));
}
```

## Backtrace

```rust
thread 'test_non_compliance_gas_cost_transact' panicked at crates/vm/levm/tests/edge_case_tests.rs:19:5:
assertion `left == right` failed
  left: 99999996
 right: 99946998
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/panicking.rs:76:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:373:5
   4: edge_case_tests::test_non_compliance_gas_cost_transact
             at ./tests/edge_case_tests.rs:19:5
   5: edge_case_tests::test_non_compliance_gas_cost_transact::{{closure}}
             at ./tests/edge_case_tests.rs:11:43
   6: core::ops::function::FnOnce::call_once
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test_non_compliance_gas_cost_transact

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 25 filtered out; finished in 0.12s
```

**Comment by DiegoCivi** [comment]
The gas deduction order has already been fixed. Right now, [`execute()`](https://github.com/lambdaclass/ethrex/blob/c3c01438d5bdbd8f7e2f0203d670613a2a821c15/crates/vm/levm/src/vm.rs#L267) will first call [`prepare_execution()`](https://github.com/lambdaclass/ethrex/blob/c3c01438d5bdbd8f7e2f0203d670613a2a821c15/crates/vm/levm/src/hooks/default_hook.rs#L30) which:

- Validates sender's balance ([here](https://github.com/lambdaclass/ethrex/blob/19097eeba57defb13af215cf50adb39d6eada412/crates/vm/levm/src/hooks/default_hook.rs#L47))
- Adds the upfront gas cost ([here](https://github.com/lambdaclass/ethrex/blob/19097eeba57defb13af215cf50adb39d6eada412/crates/vm/levm/src/hooks/default_hook.rs#L66))
- Upfront gas cost calculation = Calldata cost + Create cost + Base cost + Access list cost ([here](https://github.com/lambdaclass/ethrex/blob/19097eeba57defb13af215cf50adb39d6eada412/crates/vm/levm/src/utils.rs#L484))

**After** all this checks, the transaction execution begins. ([here](https://github.com/lambdaclass/ethrex/blob/19097eeba57defb13af215cf50adb39d6eada412/crates/vm/levm/src/vm.rs#L307))
